### ISSUE TITLE
DPU finished, than problem clearing the graph.

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1023]
There is a problem clearing the graph. 

 It tries five times or so and then pipeline finishes with error. Which parameter is used to drive how many times it tries to reconnect? 

see execution 188 on odcs-test

**Comment by janvojt** [comment]
It is also weird, that attempt is always "1" and is never incremented. I cannot find logged message "There was a problem with the database, attempt: 1, method called: clear()." anywhere in the project, I also looked in history. 

The failure tolerant repos add up to 1000 lines of duplicated code. We should replace this with an aspect, like we did with relational database. However it is in RDF module, I am not sure whether we are using spring there at all. Maybe it should be done with AspectJ.

Anyway, the configuration for reconnect attempts is in backend config. However I doubt it had much effect in this case, since attempts seem to never be incremented. It might make sense if you set database.rdf.retries = 1.

``` properties
database.rdf.retries = -1
database.rdf.wait = 2000
database.rdf.useExtension = true
```

![screenshot from 2014-01-05 10 38 33](https://f.cloud.github.com/assets/2247062/1846344/29a95030-75ed-11e3-8f1c-3b54515104f3.png)

**Comment by tomas-knap** [comment]
The log message is just in my local version, but similar log message is at the beginning of private void handleRetries(int attempts, RepositoryException ex,
            String methodName) { in FailureTolerantRepoWrapper

Yes, rdf failure tolerant repo has lots of repeated code. Let's discuss that tomorrow

**Comment by janvojt** [comment]
Related to #1043.

**Comment by tomas-knap** [comment]
Check that clearGraph is using properly loader conf "count of attemps"

**Comment by tomesj** [comment]
Yes, it is used :-)
