### ISSUE TITLE
SPARQL LOADER failed and did not retry

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1055]
Look at execution of pipeline ARES test, ODCS, execution 213.

**Comment by tomas-knap** [comment]
there is a problem clearing the graph. But anyway, the execution should try to reconnect. Why it did not try to reconnect?

**Comment by tomesj** [comment]
It´s goes about that time set on target SPARQL endpoint for query execution is less that time need for clean this graph - is is thrown this exception:

cz.cuni.mff.xrg.odcs.rdf.exceptions.InsertPartException: HTTP/1.1 500 SPARQL Request Failed. Caused by Virtuoso S1TAT Error RC...: Returning partial results after anytime timeout

SPARQL query:
CLEAR GRAPH http://linked.opendata.cz/resource/dataset/ares/or

What I found:
Restricting the language is not the way; any language beyond text search can express queries that will take forever to execute. Also, just returning a timeout after the first second (or whatever arbitrary time period) leaves people in the dark and does not produce an impression of responsiveness. So we decided to allow arbitrary queries, and if a quota of time or resources is exceeded, we return partial results and indicate how much processing was done.

More info you can see on: 
http://www.openlinksw.com/weblog/oerling/?id=1494

**Comment by tomas-knap** [comment]
Yes, but the problem is not that it was not loaded successfully, but the
problem is that it was not trying again and again to load

**Comment by tomas-knap** [comment]
Jirko, vyhod prosim ten timeout z URI, ten je tam zbytecny. Prioritu ma
stejne timeout ve virtuoso.ini

**Comment by tomesj** [comment]
OK, timeout vyhodím. Každpodádně k nahrávání dat v tomhle případě vůbec nedošlo - výjimka byla vyhozena ještě v metodě prepareGraphTargetForLoading, která předchází namotnému nahrávání - tedy o možnost opakované connection tu ještě nemohla být řeč.

**Comment by tomas-knap** [comment]
Mno, nicmene i v pripade pripravy (predpokladam, ze tou pripravou mas na
mysli napriklad mazani grafu) se muze stat, ze jednou dotaz selze (server
je vytizen), ale podruhe pri opakovani uspeje. tedy I tato aktivita (obecne
vsechny aktivity loaderu, ktere muzou selhat na problem s target
 repozitarem) by se pri nastaveni -1 v konfiguraci loaderu meli pokouset o
pripojeni znovu a znovu, bo je sance, target repozitar opravit a neprijit o
dosavadni data. Tedy prosim uprav to tak, ze i metoda clearGraph se opakuje
v pripade neuspechu. Obecne vsechny metody, ktere interaguji s target rep a
tudiz se neda predpokladat, ze dopadnou dobre.

2014/1/9 Jiří Tomeš notifications@github.com

**Comment by tomas-knap** [comment]
Jirko? Uprav to prosim tak, aby se parametr pro "pocet opakovani" uvedeny u prislusneho SPARQL loader transformeru vztahoval i na pripravne casti - tedy obecne na veskerou aktivitu s cilovym SPARQL endpointem

**Comment by tomesj** [comment]
Mám to momentálně rozpracované

**Comment by tomesj** [comment]
Reconnection problem is still fixed.
