### ISSUE TITLE
When saving pipeline, user sometimes ends on the homepage, sometimes being logged out

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1067]
As reported by Jakub, he opened the pipeline, was not working with the pipeline couple of minutes (but for sure no more than 15minutes), then he returned back, clicked save & close and he was forwarded to the homepage not the the page with pipelines. He was still logged in (at least there was user admin shown).

He has checked that it should remember him to be logged in. 

Any idea where the problem might be? 

Could be related with the logging feature - user might be logged out and then again automatically logged in. Couple of days ago, similar situation happened, but when saving & closing pipeline, Kuba was logged out. 

It happens only sometimes.

**Comment by janvojt** [comment]
This happens to me when I run multiple tomcat instances on the same host at different ports. It is because JSESSION cookie is not port-specific. Probably not, but was this the case?

Otherwise I cannot reproduce. I tried using application after 28 minutes of inactivity and everything worked fine. Please attach log if it happens again, maybe we will find something useful in there.

**Comment by tomas-knap** [comment]
Could be, there are more instances running - odcs and odcs-test

Any workaround? Is it possible to set port to that cookie? It is strage they did not think about that

**Comment by janvojt** [comment]
I looked at what the properties of cookies saved from odcs.xrg.cz are. It uses root path ("/") instead of servlet specific path. This is not the case with tomcat on my machine, which saves the cookie path correctly for each servlet instance (default behaviour). Therefore it is an issue with your Tomcat configuration.

Try looking for settings "emptySessionPath" and/or "sessionCookiePath". I am not sure how you configured it, but it looks weird. For example, it preserves both of the following paths without redirecting to a canonical URL: `http://odcs.xrg.cz/odcs-test/#!Login` and `http://odcs.xrg.cz/odcs-test#!Login` (notice the trailing slash).

> Any workaround? Is it possible to set port to that cookie? It is strage they did not think about that

This particular problem is about path, not port. Anyway, to address the port...if you look at [RFC2965](http://www.apps.ietf.org/rfc/rfc2965.html), the HTTP header for a cookie actually does have an optional "Port" parameter. This is what the documentation says about its default value:

> The default behavior is that a cookie MAY be returned to any request-port.

Another topic is browser support of this standard, which I doubt there is.

Yet another topic (if we neglect browser support) is whether JavaEE support port parameter. [Apparently not](http://docs.oracle.com/javaee/6/api/javax/servlet/http/Cookie.html).

**Comment by tomas-knap** [comment]
Honzo, neposlal bys mi prosim tvoje nastaveni tomcatu - tvoje konfiguraky?

**Comment by janvojt** [comment]
Ja mam len default. Ty potrebujes ine, pretoze chces aby ti app bezala
priamo pod domenou odcs.xrg.cz. Ja mam odcs.xrg.cz/frontend apod, kazdy
servlet ma svoju cestu.

Predpokladam ze to nastavoval Jakub Klimek, tak sa ho skus spytat ci nevie
ako to vyriesit. Ale aj tak mi pride divne, ze tam mas jeden servlet pod
"/" a druhy pod "/odcs-test". Takto sa to totiz akoby "prekryva". Ak je
servlet pod rootom, skor by som cakal ze vsetky URL pod touto domenou budu
pod rovnakym servletom.

Takze ja by som to asi bud spravil tak, ze odcs-test by bezal na inom porte
(co ale bude znamenat ze nemozes v 1 jednom browseri pouzivat oba servlety
naraz, pretoze si budu prepisovat session cookie), alebo by som nechal
default tomcat chovanie, a mal 2 podadresare odcs a odcs-test. Z rootu
domeny by si potom mohol presmerovavat na odcs napr takto:
http://stackoverflow.com/questions/8427072/how-to-forward-all-kind-of-request-from-root-to-other-web-app-context-with-tomca

**Comment by janvojt** [comment]
Can we close this and #1040 ?

**Comment by tomas-knap** [comment]
Works ok now
