### ISSUE TITLE
Document: Dataunit name => filename, if there is :, it may be a problem

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#1075]
![image](https://f.cloud.github.com/assets/718827/1932169/a87e67ea-7ec8-11e3-8e5b-26d076724904.png)

17:08:14.518 [main] INFO  c.c.m.x.o.r.r.LocalRDFRepo - Set new data graph - http://linked.opendata.cz/resource/odcs/internal/pipeline/dpu-test/0/gml:Point points
17:08:14.528 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
17:08:14.534 [main] DEBUG c.c.m.x.o.r.r.LocalRDFRepo - Unable to create data directory: C:\Users\Kuba\AppData\Local\Temp\odcs_test_1389888494410\dataUnit\0\dpu-test_0_gml:Point points

**Comment by tomas-knap** [comment]
I would suggest to add at least comment to the code/documentation of DPUs

**Comment by skodapetr** [comment]
And what about to the more power full restriction? Like the DataUnit names can be only numbers, letters and _ ?
As even when we use one line = one mapping approach then we need to somehow separate the two names on a single line.

**Comment by skodapetr** [comment]
Test use given name in dataUnit' ID in order to made easier for user to manually examine the content of DataUnit in Virtuoso, Hdd.

We do not have to use it .. then there should be no restrictions from that point of view. But still there is problem in mapping as if user use -> or ; he basically corrupt any mapping in which the given DataUnit will be used.

**Comment by tomas-knap** [comment]
Added to comment
