### ISSUE TITLE
Copy pipelines - strange names

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1088]
When I copy two times the first pipeline in the table below, I got: 

![screen shot 2014-01-22 at 4 04 20 pm](https://f.cloud.github.com/assets/3014917/1974930/946c3e0a-8376-11e3-9390-fcdc58f91e41.png)

**Comment by janvojt** [comment]
From the screen I understand this is expected behaviour for the following scenario:
1. Copy `DBpedia` -> `Copy of DBpedia` is created.
2. Copy `DBpedia` -> `Copy of DBpedia #1` is created.
3. Copy `Copy of DBpedia #1` -> `Copy of Copy of DBpedia #1` is created.
4. Copy `Copy of DBpedia #1` -> `Copy of Copy of DBpedia #1 #1` is created.

If it was reproduced with this scenario, I believe it is expected result and suggest closing this issue. Otherwise please specify the scenario, and what result you expect.

**Comment by tomas-knap** [comment]
The scenario was : Copy pipeline 156. Copy pipeline 156 once again. But it seems to be working for me now

**Comment by ghost** [comment]
Just to correct janvojt comment:
1. Copy `DBpedia` -> `Copy of DBpedia` is created.
2. Copy `DBpedia` -> `Copy of DBpedia` already exists, add suffix `#1` ->`Copy of DBpedia #1` is created.
3. Copy `Copy of DBpedia` -> `Copy of Copy of DBpedia` is created (prefix is created always).
4. Copy `Copy of DBpedia` -> `Copy of Copy of DBpedia` already exists, add suffix `#1` -> `Copy of Copy of DBpedia #1` is created.
5. Copy `Copy of DBpedia #1` -> `Copy of Copy of DBpedia #1` already exists, add suffix -> `Copy of Copy of DBpedia #1 #1` is created.
