### ISSUE TITLE
Changes saved even though user decided to discard them

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1093]
To reproduce: 
- There is DPU template
- DPU developer add one field to the DPUConfig, with no default value. 
- DPU developer replaces the template, switches to DPU template configuration. As a result, because no default value is specified, "null" is shown. 
- DPU developer switches to a different DPU template, selecting "discard changes"
- DPU developer replaces the template with a new one (where the added param has a default value). But the "null" value remained in the configuration

Possible Reason: The DPU template with the null value was saved, although user selected to discard changes

@skodape Assigning to you, because it is related with configurations.

**Comment by skodapetr** [comment]
Well, I thing that the possible reason is wrong..

If you introduce the new value .. and you deserialize (the tag is missing) then the null is assigned. If you add new value and you know about it, then you should use onDesirialize method .. check for null, consistency and update your configuration.

We may try to change this (if it's possible) but then .. does this feature, when we use default value instead of null ,bring some danger? Like .. inconsistency in config and so on. As there might be some "config-mixes" from different version as the fields were added and removed.

**Comment by tomas-knap** [comment]
Well the default value should be used only in case of missing/null value. Otherwise, if there is already some value and new default value is defined, it is not overwritten automatically. 

Alternatively, we can just add to the doc: "If you introduce the new value .. and you deserialize (the tag is missing) then the null is assigned. If you add new value and you know about it, then you should use onDesirialize method .. check for null, consistency and update your configuration."

**Comment by tomas-knap** [comment]
Petr, so the default value is used only in case of missing/null value. Otherwise, if there is already some value and new default value is defined, it is not overwritten automatically?

**Comment by skodapetr** [comment]
Well, basically it's only for import. As then the whole configuration is never null and the default values are used only if the whole configuration is null.

If you add value ... it's set to null in case of de-serialization regardless what value you assign to it in constructor as default.

**Comment by tomas-knap** [comment]
ok
