### ISSUE TITLE
Debug view/show log: Showing new log messages after clicking on the button "refresh"

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#113]
Problem: When debugging, logs appear only when the DPU is successfully executed. If there is a problem with DPU, so that it e.g. never ends, I will not find where the problem is and debug will not help me.

Solution: When debugging or running, show new logs after clicking on the button "refresh" in the show log/debug view dialog..it should show the latest logs even for the DPU currently running.

Bohuslav, tell me if this is easy to do. If not, we move to iter 4.

**Comment by bogo777** [comment]
For fetching log messages, I used pipeline execution and selected dpu instance, which I have from beginning. With every refresh, I asked log facade for all logs regarding given execution and dpu instance. So again, if logs did not show, it may be issue of when they get propagated to database.

I changed the way logs are fetched: Until pipeline execution is finished, I now fetch all logs for given execution. Only after execution is completed, I filter them by dpu instance. Also I set page to last page with newest records after each refresh.

It may clear if there is something wrong with logging and displaying log messages.

**Comment by tomas-knap** [comment]
Bohuslav, so before the pipeline finishes, if I do not select any DPU in the combo box of debug detail/show log, I will see the log messages as they are emitted for the whole pipeline run.  If I select the particular DPU before the pipeline finishes in the combo box of debug detail/show log, I will see the log for the whole pipeline or nothing?

**Comment by bogo777** [comment]
If particular DPU is selected before the pipeline finishes, log for this DPU only is showed. 

But DPUs for combo box are taken from execution context info(Because if pipeline is run only to selected DPU I do not know which DPUs are relevant to display in combo box), where they appear only after given DPU is executed.

What I described is for case when pipeline is debugged from edit screen, and run only to selected DPU. This DPU is then preselected in combo box(but only after it is finished) and until then, log for whole pipeline is displayed.

**Comment by bogo777** [comment]
Cause may be in session and transactions by hibernate. Will be solved in next iteration by #148 .
