### ISSUE TITLE
When validating pipelines, name of DPU instance should be used (not of DPU template)

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#1259]
When validating DPUs/interconnection of data units, the DPU instance name should be used, not the DPU template name. 

Motivation: see: http://odcs.xrg.cz:8080/odcleanstore/#!PipelineEdit/222

If you have time.

**Comment by skodapetr** [comment]
I think .. he use the instance name. The problem probably is that Martin copy a DPU that was at the very bottom of the canvas and so the copy was out of the canvas - unreachable for the user. 
In order to fix it I manually updated the position in database.
Canvas resizing should fix that .. on the other hand we may add some condition to prevent this from happening or insert copy always in direction to the centre of canvas.

**Comment by tomas-knap** [comment]
Ok. Yes, closing this
