### ISSUE TITLE
Strange numbering of backend/working/execution dirs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#162]
When running pipeline, I got an error:

![screen shot 2013-07-22 at 12 22 01 pm](https://f.cloud.github.com/assets/3014917/834221/a19425ec-f2b8-11e2-8748-ae01606aa229.png)

When examining the folder structure, there is no execution-60 folder but instead of that execution-52. 
1. Jirka, how are the number for execution runs assigned? 
2. Check the problem above and let me know if it may be cause by the numbering algorithm. Discuss with Petr.

My personal opinion is that it would be easier and more error resistant to use GUIDs, although their are not that nicely readable.

**Comment by tomesj** [comment]
1) Number for DPU on the concrete pipeline assignation is set as unique string ID (this ID was made by Petr) - Try to ask him, why ?....I prepared methods :-) I suggest - We can discuss about it during next meeting (tomorrow) :-)

2) I think, yoz have an error, because, we actually don´t support archives (.rar, . zip) - only files or directories :-)

**Comment by tomas-knap** [comment]
1) Well than there might be problem with ID assignment. 
2) ZIP operation is irrelevant, the problem is that it points to not existing working directory

**Comment by tomas-knap** [comment]
i switch to Petr, because he was doing the assignmment of IDs

**Comment by skodapetr** [comment]
"When running" does that mean that the pipeline execution is not in "debug mode"?
