### ISSUE TITLE
When restarting pipelines, how is that shown in the execution monitor?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#168]
Currently, when I twice restarted backend as the pipeline JTagger was running, the backend always tried to be run again, but sending events and logging to the same record in pipeline execution monitor!

![screen shot 2013-07-24 at 12 37 13 pm](https://f.cloud.github.com/assets/3014917/847966/42dbff66-f44d-11e2-868b-5b7d8a943661.png)

As you can see, there are three events that DPU extractor has started.

Solution: When restarting pipelines, new pipeline execution monitor record should be created and the previous one should end with the status failed

**Comment by skodapetr** [comment]
For iter 3. this can be solution but maybe for iter 4... 
But in future .. the pipeline should start when it ends (in terms of DPU) in case of backend shut down. So maybe message about this will be sufficient?
Because the pipeline execution does not really failed .. like in case of error just has been interrupted (paused) and then resumed.

**Comment by tomas-knap** [comment]
Yes, that is true, maybe there could be some state that the pipeline was interrupted, when being executed. Similarly, if we would like to rerun the pipeline because of e.g. edited pipeline definition, similar state may be needed (pipeline was interrupted because new definition available)

**Comment by tomas-knap** [comment]
See also #215

**Comment by tomas-knap** [comment]
I saw there is an extra event that the pipeline was restarted, so we can close this issue?
