### ISSUE TITLE
Debugging from canvas - buttons and blinking of the scrollbars

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#189]
Please add button "Close" and "Rerun" when debugging from canvas.

Rerun will simply start the same debugging process (debugging for the same selected DPU) again in the same window. 

Also check the blinking of the scrollbars as the dialog is refreshed. After every refresh, the horizontal scrollbars in the tables with logs/events appear and then dissapear, and again and again.

**Comment by tomas-knap** [comment]
Is that complicated to realize or matters of few hours? Can you estimate?

**Comment by bogo777** [comment]
Buttons are not problem.

For blinking and scrollbars I wanted to try addind new items to container on refresh, instead of passing new container every time. But there must be some support from DAO and not all containers support this. I also do not know if it will help. But I would leave this part after solving #220, where we will possibly use new custom container.

**Comment by tomas-knap** [comment]
So to summarize, blinking of scrollbars is still an issue, will be solved when #220 done
