### ISSUE TITLE
Config to connect to DB in web.xml for tomcat

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#207]
Create config file for tomcat in web.xml. Such config file for tomcat should contain minimum of duplicating configurations from config.properties, ideally only connection to the relational DB, which frontend needs.

based on the findings in #124

**Comment by janvojt** [comment]
Do I understand this correctly?
1. Is it true that the configuration of virtuoso in config.properties should be duplicated in web.xml?
2. Which configuration takes precedence then?
3. Is it still true, that if config.properties is not present, frontend dies?
4. Is this only about virtuoso configuration? (I think frontend requres also backend._, email._ and module.path)

**Comment by jakubklimek** [comment]
No, frontend should not read config.properties at all. All necessary configuration must be in web.xml, part of the frontend WAR. This is common for tomcat web applications.

**Comment by tomas-knap** [comment]
We will discuss that tomorrow f2f

**Comment by janvojt** [comment]
Well, this would mean we duplicate majority of config.properties into web.xml. I think this is really unnecessary if frontend and backend runs on the same machine. Maybe a better solution would be to specify a path to config.properties in web.xml?

**Comment by jakubklimek** [comment]
1) There are 2 identical config.properties files even if ODCS runs on the same computer (one in the home of the user running backend and one in the home of user running frontend, which is a problem especially because SYSTEM user on Windows does not have a home and the location is then C:.intlib\config.properties, which is just wrong), so from that point of view, it is not much worse.
2) Who said that backend and frontend runs on the same machine? We should not presume that. On the contrary, we should test this configuration (DB on one machine, frontend on another and backend on another). Is there even a way how to say on which machine the backend runs?

**Comment by janvojt** [comment]
1) If you run on the same machine, you can just make a symlink. Or you can even run under the same user. I agree that having C:\.intlib is wrong, but even worse is, that system user on Windows is homeless. :D Anyway, this would be addressed by my suggestion to specify config path in web.xml.
2) I do not presume they run on the same machine. It would just be easier for developers to update one config file, instead of two, as they usually run on the same machine. On top of it, web.xml is versioned, so it would cause conflicts if it is changed, and also someone might commit his configuration (with passwords) by accident.

The host and port backend listens on is the following section in config.properties (it is used by both, frontend and backend):

```
# Backend application configuration
backend.host = 127.0.0.1
backend.port = 5010
```

As Tom said, we will discuss this at the meeting. I am not saying current solution is ideal, but it seems to me better than always having two duplicate configurations (sidenote: I am not a windows user).

**Comment by tomas-knap** [comment]
2 config files -> jeden pro backend (tak jak je), pro frontend config.properties vlastni, ve WARku. Pozor aby se nedaval do gitu

**Comment by tomas-knap** [comment]
Honza, please adjust that till tomorrow. I will need this, so that I can run two instances(realease 0.4.1 and devel) of the tool on odcs.xrg.cz. Without configuration in web.xml, I would need to run the two instances of frontend under two different users.
