### ISSUE TITLE
DPU template - button "Reload JAR file"

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#249]
Motivation: Possibility to reload jar file for the existing DPU template

Solution: Add button "replace" next to the JAR file name. When clicking on that button, it behaves like clicking on the "choose file" in create DPU template - user may select the updated version of the JAR and, as a result, such version is uploaded. Status of that upload is shown 

![screen shot 2013-08-19 at 4 09 42 pm](https://f.cloud.github.com/assets/3014917/986453/6bf0fa64-08d9-11e3-8fe9-00dfef115d8c.png)

**Comment by kukharm** [comment]
Tomas, could you sent me some JAR file of extractor, transformer or loader that is not default in the project, please. I need it for testing functionality.

**Comment by tomas-knap** [comment]
Maria, please try any DPU in DPUs repository - https://github.com/mff-uk/DPUs

Tell me if that worked for you

**Comment by kukharm** [comment]
I tried Extractor_psp_cz_metadata-0.0.1 but during upload i get  "Unknown DPURecord type" exception that appear in case if type of jar  (Extractor, Transformer or Loader) not defined. Furthermore I was unable to download this jar as new DPU template because of this exception. When i try JTagger_Extractor-0.0.1 & Simple_XSLT-0.0.1 i get ![ex](https://f.cloud.github.com/assets/3471169/1086752/09fdf84a-1606-11e3-8b8e-f772d2e598fc.jpg)
also i can't upload it with help of "create dpu template" button too.

**Comment by tomas-knap** [comment]
ok, so please copy some core module - for example RDF etractor - adjust the name basically and test it on that please

**Comment by tomas-knap** [comment]
Maria, did that work for you?

**Comment by kukharm** [comment]
When i reload the same jar that is already in project (but with another name) i  get duplicate bundle exception. Yesterday i talk about this with Petr, he said that there some problem with it and  need discussion.

**Comment by tomas-knap** [comment]
Petre,Maria, so what is the status? Is it prepared for testing?

**Comment by skodapetr** [comment]
Tomas: Actually I experience problem with security  "An authentication object has not been found .." when I click on "Replace" button and select file to load. Please test and it there really is that problem reassign to Honza .. or write otherwise
