### ISSUE TITLE
Automatic refresh not working 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#255]
Automatic refresh not working  for execution monitor records, details about events/logs in debug view/show log. Can you please check that?

**Comment by tomas-knap** [comment]
Bohuslav, please update me on this issue

**Comment by bogo777** [comment]
Automatic refresh worked for me on canvas, but I currently have some issue with loading DPUs(propably missing some jars in lib folder) and execution fails, so I do not have enough time to try it from execution monitor.

**Comment by tomas-knap** [comment]
Bohuslav, but when you launch pipeline dbpedia, switch to execution monitor and then wait, the execution monitor does not refresh automatically when the pipeline is ready. The pipeline is still in the state running in the execution monitor, but it has already finished. Can you reproduce this?

**Comment by bogo777** [comment]
Ok, I see where the problem is, I started automatic refresh as feature of DebuggingView, because it is used both for debugging from canvas and execution monitor. I added refreshing of execution monitor by firing event on DebuggingView. But when there is no execution selected, execution monitor doesn't refresh itself.

I will fix this.
