### ISSUE TITLE
Unable to version DPU projects

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#261]
When creating a DPU project JAR, it has version 0.0.1 by default. I can set dpu.version in pom.xml file to 1.0.0 but it still creates a 0.0.1 file. When I set &lt;version&gt;1.0.0&lt;/version&gt; to the pom.xml file, it starts to look for all dependencies in the 1.0.0 version and fails:

<pre><code>[WARNING] The POM for cz.cuni.xrg.intlib:commons-web:jar:1.0.0 is missing, no de
pendency information available
Downloading: http://repository.springsource.com/maven/bundles/release/cz/cuni/xr
g/intlib/commons-module/1.0.0/commons-module-1.0.0.pom
[WARNING] The POM for cz.cuni.xrg.intlib:commons-module:jar:1.0.0 is missing, no
 dependency information available
Downloading: https://repository.jboss.org/nexus/content/repositories/thirdparty-
releases/cz/cuni/xrg/intlib/RDF/1.0.0/RDF-1.0.0.pom
Downloading: http://repository.springsource.com/maven/bundles/external/cz/cuni/x
rg/intlib/RDF/1.0.0/RDF-1.0.0.pom
Downloading: http://repo.maven.apache.org/maven2/cz/cuni/xrg/intlib/RDF/1.0.0/RD
F-1.0.0.pom
[WARNING] The POM for cz.cuni.xrg.intlib:RDF:jar:1.0.0 is missing, no dependency
 information available</code></pre>

Is there any way to correctly version DPUs?

**Comment by tomas-knap** [comment]
The versioning of DPUs should not be dependent on the versioning of the tool, so ideally, regardless of version specified in DPU pom.xml, the latest version of the tool should be used.

**Comment by skodapetr** [comment]
I do not know about possibility to automatically use latest-parent. 

But to specify DPU version one should use property 
`<dpu.version>0.0.2</dpu.version>` so imho it's independent in certain point of view.

That will affect the "version of the code" but does not change the version of the parent project. I will commit some changes that will propagate the dpu.version into bundle-version as well to make the change more visible in final manifest file.

**Comment by jakubklimek** [comment]
Yes, I can use the dpu.version property, but as you pointed out, that is not visible anywhere. What I however can see is the version of the resulting jar file.

Strange thing is that in the pom file I left the version of the parent as 0.0.1 and only added version which should be of the current DPU. But that did not work.

**Comment by skodapetr** [comment]
It was visible (even before update) in the last line of manifest.mf in exportet-package, but if do not know where to search I agree that it is "invisible".

To the described behaviour .. when the jar's manifest file is created it use version to determine the version of required libraries as can be seen from error message. If you set version in DPU .. you override the setting for version in parent pom.xml as well.

Maybe we can update the pom.xml file of the module parent project .. and use special variable to determine version of the used packages .. and then use classic version property instead of dpu.version property. 
We can discuss it with Tomas on our next meeting.

The drawback I can see here is that now all is in single element property but after this change one value gets out of the property element so the won't be on single place.

**Comment by jakubklimek** [comment]
I think that the element not in single place is a small price to pay for being able to version properly.

**Comment by tomas-knap** [comment]
dpu.version removed, instead of that version is used. intlib version is used for version of the core

**Comment by tomas-knap** [comment]
DPU - pom.xml
- use version instead of dpu.version 
- use description instead of dpu.description
