### ISSUE TITLE
RDF File Loader (and similar DPUs) should display some basic settings directly in the box

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#263]
When I have an extractor with multiple outputs and I want to save each of them to a different file, I need to use multiple RDF File Loaders. It gets confusing as I don't see the file name of the output file directly in the box of the file loader.

I would expect to see some basic settings directly in the box instead of a description. I already know that RDF file loader loads RDF into files. I don't need to see that again. Instead, show me to which file it loads.

This also applies to similar other DPUs.

**Comment by skodapetr** [comment]
I thing it's possible to modify that text from DPU configuration dialog. So it's possible to add the output file name into description. 

But maybe it's not a bad idea to add some button, that enable the configuration dialog (provided by DPU author) to specify this description?

Ad. to the saving multiple outputs .. I'm no sure if that is possible in current version with current loader.

**Comment by jakubklimek** [comment]
OK, the description should be configurable by the dialog author.

Ad. multiple outputs: I thought that that is what the named edges are for - to specify which data unit the next DPU should take.

**Comment by skodapetr** [comment]
Ad. multiple: Yes but the file loader did not support this. 

But it takes less then minute to update it. So please rename dataUnit that should be stored by FileLoader to "input". If there are more dataUnits with this name only the first one is taken.

Unfortunately I'm currently working on another issue so I can't test this functionality now.

**Comment by tomas-knap** [comment]
I would suggest to show tooltip when mouse is over certain DPU -> the tooltip can be obtained by calling getConfigurationSummary() method which the DPU developer may redefine. By default, it will show description. 
What do you think?

Regarding input/outputs, discussing is needed, contribute to #280

**Comment by jakubklimek** [comment]
I don't agree. These things should be visible without hovering to getting a tooltip. I would do it the other way around. Description in a tooltip and settings in the box. When one uses the DPUs for some time like we do, we already know which is for what so we don't need nor read the descriptions. We however need to see the settings like to which file/graph/... the pipeline puts data, where it gets it etc. directly at first glance on the pipeline.

**Comment by tomas-knap** [comment]
Kubo, the problem is that if we put all such information directly to the DPU box on the canvas, the box will be quite big and not much DPUs could be visible at one time or the font of the description would have to be rather small. That  was the motivation for tooltip

**Comment by jakubklimek** [comment]
Not all, just the important one. Like the file name in the RDF file loader, graph name in RDF graph loader etc. That should be up to the DPU developer to keep it simple but efficient.

**Comment by tomas-knap** [comment]
Yes, but e.g. named graphs ten to be quite long, so it would need extra logic which hides the prefix of the named graph e.g. Otherwise, the DPU boxes on the canvas would look really ugly. On the other hand, long tooltip is completely fine and no refinement is needed.

**Comment by skodapetr** [comment]
I thing that it can be sometime useful to define the description on your own. Just imagine using multiple SPARQL transformers .. the query is too long to be used as a description and there is no other value in configuration.

On the other hand using description from configuration is probably better for loader,file dependent DPU, etc ..

So I propose the following solution:
1)  add method getConfigSummary to the configuration which user may redefine .. the purpose of this method is to provide configuration summary 
2) add check-box to the dialog .. (default true) if user want to use the getConfigSummary as description (default true) or use user provided description. 

There will be always only one stored so when used change from user to config-provided and save the DPU then the user-provided description will be lost forever but he can switch back and provide other description

**Comment by skodapetr** [comment]
The tool tip seem fine to me for some use case ..  maybe for DPUs  with user provided description? 

So I can not only see me description if I want but I can also quickly revise important aspect of the configuration?

PS: We can check the length of getConfigSummary and if too long warn user about it .. so he may decide not put it into the description. Because for example what is too long on 13,3 monitor can be fine on 21.

**Comment by tomas-knap** [comment]
I think that the checkbox is not needed, if the user redefines certain methods, his definition will be used. 

What about having two methods, e.g.:
getToolTip() and getCanvasText(), which the DPU developer may redefine. If they are not redefined, the first returns nothing, the second one getDescription(). If redefined, the first defines the content of the tooltip and the second one the text under the DPU name. If the canvas text is too long, we may cut it off.

**Comment by skodapetr** [comment]
But in that case when DPU author redefine certain method I as user can't give my description to the DPU .. 

even worse I can give my description only to some (based on something I can't see) and in my opinion this can be confusing for some people: why I can add description to this and not to this?

**Comment by tomas-knap** [comment]
The problem is that for certain DPUs, the description is not that interesting as for the others. If I upload certain rather specific DPU for particular use case, description is what the user would like to see. But if I use the core DPUs, which will be used often by the user, it is a waste of the space to show always the description. Maybe we can combine these two methods with the checkbox in the Settings menu item, where user may specify whether he would like to always see original descriptions or the results of the redefined methods? Alternatively, we can provide checkbox for each DPU, where user may specify the same but for each DPU

**Comment by skodapetr** [comment]
I'm for checkbox for each DPU with default value -> use getConfigSummary
It will give user freedom to decide on his own.

It will require:
- small change in DB (adding check box value)
- update configuration interface
- introduce new class BaseConfig with empty implementation of this methods (for easy use)
- implement in core DPUs 
- add checkbox to the dialog and if need use value from getConfigSummary value instead of value from description dialog
- also disable the textarea in dialog if the checkbox is checked
- maybe warning dialog for using long description? 

Also this can be implemented before the users which are to my knowledge not currently fully available.

**Comment by tomas-knap** [comment]
Petre, just the question is if the change is not to complex for the feature we gain. because, still, we can rely that DPU developers are those who know what they are doing, so it is their intention to provide understandable DPU - provide reasonable implementation of getDescription method. And still, description in the original form may be presented in DPUs menu item when browsing templates

**Comment by tomas-knap** [comment]
getToolTip() - maybe later, postponed
