### ISSUE TITLE
Login: Very short time for working

### ISSUE THREAD

**Issue by tomesj** [mff-uk/odcs#324]
When I login to INTLIB, it shown our splash screen. When I choose anything (Pipeline, Execution Monitor,...) login screen is showing to me and I have to login again ?

I used 
login: admin (and user)
password: test

Where is problem ? I think, that it could be may be something like short session , but if I use another application I have no problem with session or cookies.

Is it OK by you ?

If there is problem, Tomas, please assign responsible person for that - probably Honza or Bohuslav .

**Comment by bogo777** [comment]
Honza made authentication, I don't see any timeout in it at first glance. 
But for me only one login is necessary, then I can work normally without loging in again. Only when I change something in GUI and reload the application I have to log in again. But that is correct.

**Comment by janvojt** [comment]
I cannot reproduce this either. Can you please try clean&build on project, redeploy to tomcat, and clear browser cache and cookies and try again? Post your results.

I used spring security for handling session, and the default timeout should be 30 minutes. Generally in Spring Security this can be changed on HTTP session object. However vaadin tries to hide HTTP communication, so I am not sure how to change it. It would require more research. I believe 30 minutes is OK for timeout, but in future it would probably be better to add session timeout setting to configuration.

**Comment by janvojt** [comment]
There was a problem with security context not being saved to session by Spring Security. Because of that, security context was bound to a tomcat thread. Then the login status depended on the thread worker that was chosen to service request = pretty random.

After few days wasted on trying to setup spring security filter chain and make it work with websocket connections and custom vaadin login form, I gave up and handled reloading authentication from session myself. Relevant commit is e2853bf9.
