### ISSUE TITLE
DPU Templates - save, delete buttons 

### ISSUE THREAD

**Issue by kukharm** [mff-uk/odcs#380]
The buttons save and delete in the DPU templates now available in accordance with the user permission  (as i understand from the code). When i was logging as admin and as user this buttons were disable in each case. Could you please explain  in which case buttons are enable. I need it for solve #246

**Comment by janvojt** [comment]
First pull the latest version, I commited an important fix concerning authentication and authorization.

To explain:
Owner of all DPUs is admin. All 5 DPUs versioned in database are public. Owner can perform all actions, so all buttons are visible for him. Since they are public, user "user" can see them and can copy them (he should also be able to export them as I think of it now, I will adjust appropriately).
