### ISSUE TITLE
Status Schedulled in execution monitor - questions

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#392]
1. It may be rather condusing that you may set up schedulled events in the scheduler menu item and they do not appear in the execution monitor. But when you run pipeline and backend is offline, there are certain schedulled events in the execution monitor which are not result of the scheduler.  
2. If I click cancel on the pipeline being in the status schedulled, what should happen? Should there be execution records associated with such pipeline run?

**Comment by skodapetr** [comment]
1) it can be .. but the Scheduler component is managed by backend .. also the question can be how mane execution there should be? I can imagine solutions that would be much worse then current implementation.

2) I thing we can delete automatically and immediately executions that has no data in context, it. nothing happened to them.  As to cancelling scheduled pipeline rather then changing state I would suggest use "stop" attribute. The reason is simple: 
- backend can read records into memory as Scheduled
- use cancel ie. change to Cancelled
- backed start execution threat and then change state from Scheduled (as he has it in memory) to Running and save into database
  as a result .. user will be confused. 

solution 1) If we use "stop" then before executing the very first DPU backend check .. and if "stop" is true .. then cancelled the execution. But there will be record about execution left .. 

solution 2) or we can immediately delete the execution when user cancel scheduled execution .. then backend got "Record has been deleted" exception and can terminate the run. The disadvantage is .. that there can be DPU running ..  it can take system resource run for several ours .. and there will be no evidence about it. This is why I personally prefer the first solution.

**Comment by tomas-knap** [comment]
Proberem na schuzce, davam tag toDiscuss

**Comment by skodapetr** [comment]
Take teď používám status Scheduled .. pro obnovu pileline po pádu backendu ... tj. mazání scheduled .. je jako mazání dokončené, tj. musel by se sebou brát i kontext .. a to umí jen backend.

**Comment by tomas-knap** [comment]
Tasks to be done: 
1) Change the label for schedulled state to queued (before execution)
2) Exec monitor -> record which is schedulled (queud) should not be deleted, but should be cancelling (after pressing "Cancel" and then moved to cancelled by backend

**Comment by skodapetr** [comment]
1) has been done by Bohuslav
2) is also ok .. 
so I think we can close this.
