### ISSUE TITLE
Execution monitor refreshes logs, not pipelines

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#397]
Related to https://github.com/mff-uk/intlib/issues/383

When looking at logs in Execution monitor and the pipeline finishes, its status is not refreshed and still shows as running.
![image](https://f.cloud.github.com/assets/718827/1097669/b06d0c26-1713-11e3-9e02-b40ff2fdfcb8.png)

**Comment by bogo777** [comment]
There is lag between failed DPU event and time when backend marks execution as failed. I think it is due to cleanup. After pipeline is marked as failed(or finished any other way, checkbox "Refresh automatically" dissappears from right part and at the same time the status of execution should be changed).

**Comment by jakubklimek** [comment]
Well, not in this case. It stayed like it is on the screenshot. From the log it is apparent that it is already failed.

**Comment by skodapetr** [comment]
Bohuslav is right .. there has been certain lag after last DPU finished/failed and the end of the execution because of cleanUp. Unfortunately it is not now .. as I save the data first and after that I do cleanUp. 

What we can try is to open another instance of frontend and check if the Pipeline is still in running state or not as I ting that this information can be helpful or add log into frontend that will announce regular checks and their results.

**Comment by bogo777** [comment]
Sometimes refresh thread got stuck on NPE and didn't recover from it. I adjusted it, so it shouldn't happen anymore.
