### ISSUE TITLE
SPARQL Loader - division by zero if no data available to load

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#449]
Jirka, if there are 0 triples to be loaded, division by zero. 

![screen shot 2013-09-11 at 9 44 50 am](https://f.cloud.github.com/assets/3014917/1121024/2141ced2-1ab6-11e3-88ab-f9a5ec8f97b3.png)

**Comment by tomesj** [comment]
This problem is only in pipeline (SPARQL loaders) which were created before adding textbox with chunk size. This information is not in DB a those DPUs must be set again - if you open it, there is a validator for this. You can not safe it, if the value is number, or if this number is less or equals than 0.

If you create new pipeline or add new SPARQL loader - you have set default value 100. 

I will add checking it in load method again and in case of problem I throw RDFException.
