### ISSUE TITLE
Cannot display all logs

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#488]
In the currently deployed version on odcs.xrg.cz when I selected that I want to see ALL logs:

![image](https://f.cloud.github.com/assets/718827/1145262/998a2f84-1e02-11e3-977d-eac003c7db19.png)

**Comment by janvojt** [comment]
I cannot reproduce this, not on my machine, not on the current deployment on odcs.xrg.cz. Is this still relevant?

**Comment by jakubklimek** [comment]
It is. Even though it is not easily reproducible, it still happened when it should not. Have you looked at the source line (from the exception) to see if there is anything suspicious? What could cause an exception like this?

**Comment by janvojt** [comment]
It could be, that attribute "level" is transient. We are persisting "levelString" as a String, and then resolving it to enum in getter. LazyQueryContainer has a "level" attribute defined. However if this is the problem, it is suspicious that this exception does not happen all the time. Bohuslav might know more about how LQC is using this attribute, because he authored it. I am reassigning this.

**Comment by bogo777** [comment]
LQC is using "level" attribute for getting values for level column. It uses getLevel() method. For filtering, there is custom filter, which uses "levelString". For sorting, LQC looked directly for db representation of level, which is none and there was error. But sorting is disabled for a few days, so it should not happen anymore.

**Comment by jakubklimek** [comment]
And why is sorting disabled?

**Comment by bogo777** [comment]
Sorting can be enabled/disabled only for whole table, but data type of message column doesn't allow sorting. I disabled filtering on that column on Honza's request with this explanation and sorting didn't work for same reason, so I disabled that, too.

**Comment by jakubklimek** [comment]
Well, this is a problem. There has to be sorting and filtering. Why would Message data type not allow filtering? It should do a full-text search on the message field. Have you discussed disabling it this with Tomas?

**Comment by bogo777** [comment]
All I know about this comes from Honza, issue #485. It is for different table/column, but the resulting error is the same.

**Comment by jakubklimek** [comment]
OK, I reopened #485 until Tomas can say what to do about it. Disabling it is not acceptable. As to this issue, there has to be another cause, so keep looking.

**Comment by janvojt** [comment]
Well, the resulting error is not the same. Error here is caused by the fact that attribute "level" is transient. But I suspect this bug comes from some old revision and does not occur anymore. If we cannot reproduce it in the current version, I believe we should close it.

If you want to inspect it further and find out why exactly this happened, we should inspect the commit on which this error was reproduced. Although I believe it would be just a waste of time...

**Comment by jakubklimek** [comment]
OK, we'll reopen this if necessary.
