### ISSUE TITLE
Add "Conflicts" to Pipeline Description

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#491]
Add "Conflicts" to Pipeline Description

Conflicts are other pipelines.

If a conflicting pipeline runs, the current pipeline cannot start.
Don't forget to deal with the scheduling implications

**Comment by tomas-knap** [comment]
I would opt for a simpler solution: Just adding one checkbox to pipeline detail "allow only one instance of this pipeline at once. " As a result, it is ensured that this pipeline is running only once at certain time. 

Similarly, for DPU template you can check "allow only one instance of this dpu running at once." As a result, certain DPU (and all DPUs inherited) may be launched only once. 

Kuba, Petr, what do you think?

**Comment by jakubklimek** [comment]
Ok, for a start

**Comment by tomas-knap** [comment]
Petre, so please ask Bohuslav to prepare the needed checkbox and iff needed, ask Honza to persist the selection. Then ensure that such selection is enforced when pipeline is launched. 

If certain DPU/pipeline should be run only once and is alraedy running and the user runs/debugs the pipeline manually, an error occurs. If schedulled event cannot run due to already running pipeline/dpu which must be run only once, than either skip the current planning or reschedule for later, see #526 (Jakub will add)

**Comment by tomas-knap** [comment]
I put this to iter 0.5 (October), with high prio

**Comment by skodapetr** [comment]
Do we need "conflict" for whole pipeline? What about conflict for "DPU"s? 

I would suggest some kind of annotation like "OneAtTime" which secure that at most one execution method at time is running. There still can exist multiple instances of DPU.

**Comment by skodapetr** [comment]
There is now support from database and backend. The next step should be support from frontend and then testing. So I propose to re-assign to Bohuslav-Maria or someone else base on their workload.

**Comment by tomas-knap** [comment]
Petre, pridej prosim popis toho jak to tedy nakonec funguje do confluence, staci strucne. In terms of GUI, what is needed? Please specify here

**Comment by skodapetr** [comment]
Every pipeline now contains filed List<Pipeline> conflicts. 

So we need a new component/dialog that enable user to work with this list, then we can test this functionality.
The dialog should contains list of all pipelines .. probably for every user? - we should discuss this with Jakub
user can use checkBox .. (probably simplest solution) to select conflict Pipelines .. also we have to remember that the pipeline can have conflict with itself .. ie. only one instance can be running at time.

**Comment by tomas-knap** [comment]
Write Maria how the dialog should look like and document.

**Comment by skodapetr** [comment]
The mockup is ready for @kukharm , so I reassign to her

**Comment by skodapetr** [comment]
I update the dialog .. and do a simple test to test the functionality. The screens shows the results:

First the conflict dialog:
![dialog](https://f.cloud.github.com/assets/3341693/1714111/dbeaa99a-619a-11e3-84a6-ca4c240dd1ce.png)

Then the message log which show that the pipeline waits:
![detail](https://f.cloud.github.com/assets/3341693/1714106/becd412e-619a-11e3-929d-bd39d3a9e9f6.png)

I also reassign back for testing .. as I'm responsible for the functionality.
just @kukharm :please update the mockup according to the changes that we have decide to do in order to simplify the implementation of the dialog.

**Comment by kukharm** [comment]
mockup update https://grips.semantic-web.at/display/LOD2/Pipeline+conflicts
