### ISSUE TITLE
Error when creating a pipeline

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#496]
Now I just created a pipeline from normal DPUs, connected them with an edge, played around with alignment (got stuck - could not get rid of the alignment buttons btw) and then I clicked Save and close and I got:

![image](https://f.cloud.github.com/assets/718827/1147465/23637a82-1ea6-11e3-9a10-d4346fe5cb31.png)

**Comment by tomas-knap** [comment]
Honza, please check that, use the access to virtuoso I sent via email to see the db content

**Comment by bogo777** [comment]
Were there some DPUs that were added on canvas and then deleted? Or just those 2 on the screenshot with single edge? I'm trying to reproduce it.

To Honza: I remembered about something that may be related. When deleting DPU from canvas, I keep it in list and upon save explicitly delete it via DPUFacade. It was needed for proper functioning before. I tried to remove this code and it seems to work, too. So what is the right way to do this?

**Comment by jakubklimek** [comment]
No, in this instance, there were no deletions. Just playing with align.

**Comment by janvojt** [comment]
First we should find steps how to reproduce this. Without them we are just guessing.

My guess is, that DPU node was loaded, deleted, and then an attempt to save it was made. The deletion may have happened by a different user. The fact that the node is on canvas means, that the node existed physically in the DB when canvas was loaded. The exception upon save says, that the node is not present in the DB. Therefore it must have been deleted in the meantime somehow.

Again, it will be easy to see the problem once we have the steps to reproduce this.

**Comment by bogo777** [comment]
I found a way to reproduce it.
Create pipeline with one DPU. Save it. Delete DPU. Try to save it. It does it for me.
If you don't have latest version(pushed now), you must reload pipeline from pipeline list after first save, due to #503.

**Comment by janvojt** [comment]
I also found an interesting bug, most likely related:
1. Create new pipeline
2. Name it
3. Click Save
4. Add a dpu
5. Click Save
6. Move DPU
7. Click Save and Close
8. Open the pipeline again, and you have 2 DPUs! :)

**Comment by jakubklimek** [comment]
Nice :+1:

**Comment by bogo777** [comment]
Honza's bug was related to my fix of #503. I repaired that and hopefully this issue too. DPU Instances are still explicitly deleted, which is needed, but only after the pipeline is saved. 

I think that deleting them before, deleted also their nodes due to reference, and they weren't in the database at time when saving pipeline, which should delete them.

**Comment by janvojt** [comment]
OK, Bohuslav fixed this.

The original idea was, that when pipeline is saved, orphan nodes are deleted. However I think this only works, if pipeline entity is managed by hibernate session (=transaction) in which it was loaded at the time nodes are removed from the collection. This is not the case, and never will be, because we do not want the transaction to be active throughout the whole process of editing pipeline.
