### ISSUE TITLE
Configuration validation fails

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#501]
I used my DPU, which obviously has an error in configuration validation. However, using it, discovered a bug in DPU validation.

While doing configuration in Dialog, I probably entered something that fails the isValid check. However, nothing happened.

The error came when I ran the pipeline containing the misconfigured DPU. Then, when I wanted to edit the pipeline and opened the dialog, it erased all the configuration and said that configuration was not valid and that it is using defaults. But all the fields were empty.

1) What defaults? Apparently it does not work
2) The check should be performed immediately when trying to save the configuration

![image](https://f.cloud.github.com/assets/718827/1147689/d149bcd2-1eac-11e3-9dcd-274050fea18f.png)

**Comment by skodapetr** [comment]
Reassigned to me as I'm "author" of this functionality. 
According to documentation the DPU dialog should throw exception if it contains invalid configuration. But it's true that we can add isValid check. But I see some detail that we may need to discuss.

There is again maybe a problem with no-rich-descriptive exceptions.
 In this case .. the configuration is invalid (isValid return false as you said), so there is message "invalid configuration". So no configuration is set to the dialog, which mean it use "dialog default", which is just the dialog as it is. So if you do not provide some "default" values in dialog .. then the dialog is empty. Yes this behaviour is something we can discuss.

To discussion: 
- Set invalid configuraiton to the dialog in order to retrieve at least some settings?
- Should the dialog have possibility to throw Exception in case of invalid configuration. The configuration validation may require context?
- Should we double validate the configuration .. ie. by dialog and by isValid before save?
