### ISSUE TITLE
Prepare methods for exporting Logs from DB when "Download" button pressed on debug view->logs tab

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#522]
please follow the specification/mockup:
https://grips.semantic-web.at/display/LOD2/Debug+Pipeline

related to #520

**Comment by bogo777** [comment]
Currently all logs for selected execution are downloaded. Is it ok or should only filtered logs be downloaded?

**Comment by tomas-knap** [comment]
If it is not complicated, only the logs which satisfy the conditions defined by the filters before clicking on the download button should be downloaded. It is more flexible and behaves as expected by the users. Can you adjust that easily?

**Comment by bogo777** [comment]
I almost have it, only thing that remains is incorrect filtering by DPU and execution. With that, I need help from @janvojt . It is in new method getLogs(PipelineExecution pipelineExecution, DPUInstanceRecord dpu, Set<Level> levels, String source, String message, Date start, Date end) in Logfacade. 

I want to select log by execution and DPU, but the used query is incorrect. I get this error:
Exception Description: Problem compiling [SELECT e FROM LogMessage e WHERE e.levelString IN :lvl AND (e.properties[:propKey] = :propVal) AND (e.properties[:propKeyDpu] = :propValDpu) AND (e.message LIKE :message)]. 
[60, 82] The state field path 'e.properties[:propKey]' cannot be resolved to a valid type.
[100, 125] The state field path 'e.properties[:propKeyDpu]' cannot be resolved to a valid type.

Other way this this is tried to accomplish is in method getLogs(PipelineExecution exec, DPUInstanceRecord dpu, Set<Level> levels).
But that returns all logs for given DPU and all logs for given execution. (But when there was AND instead of OR it didn't return anything...)

**Comment by bogo777** [comment]
Solved by inspecting query for container.
