### ISSUE TITLE
Possibility to sort in tables, such as logs/events, ..

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#531]
As the queryBuilder is used, it is not possible to sort by certain columns. Reenable this property as discussed on the meeting

**Comment by bogo777** [comment]
I enabled sorting in events table, except for message column, where sorting is not possible due to its db data type.

In logs table, currently there are no sortable columns:
Date is initialized from long in getter and Level from string, they have no direct db representation, and there is no way to generate custom sort as is for filter. I think I have a solution, but it will be more work, than simply setting sorting enabled.
Message is unsortable due to its db data type.

Table in pipeline list is sortable and I will explore execution monitor main table, where sorting doesn't work.

**Comment by tomas-knap** [comment]
Ok, thanks for the report, sorting for message column does not make much sense, so it may not work, that is fine. Please focus  on sorting of the execution monitor and then prepare for yourself the issue with milestone 0.5 to allow sorting of date & level in logs.

**Comment by bogo777** [comment]
Closed, rest if issue moved to new issue #570
