### ISSUE TITLE
When running pipeline, malformed input is shown

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#579]
![screen shot 2013-10-03 at 12 14 50 am](https://f.cloud.github.com/assets/3014917/1257872/2b57ce8e-2bb0-11e3-9e41-79a7a12c131d.png)

To reproduce: GO to odcs.xrg.cz:8080/odcleanstore and try to run any pipeline.
Honza, please look on that when #572  is done.

**Comment by tomas-knap** [comment]
When testing on new fresh db, it does not occur, at least not for dbpedia pipeline

**Comment by tomas-knap** [comment]
Koukam, ze po aplikaci update scriptu mi u stavajicich pipeline u core DPUs otevreni DPU detail hlasi: 

Unexpected exception configuration object a conf je prazdna. 

Co je pricinou? Mozno vyzkouset na odcs.xrg.cz:8080/odcleanstore u dbpedia pipeline

**Comment by tomas-knap** [comment]
Aha, uz vim, v conf je: 

<pre>
object-stream cz.cuni.mff.xrg.intlib.extractor.rdf.RDFExtractorConfig ..</code></pre>

Je treba zmenit na cz.cuni.mff.xrg.odcs.extractor.rdf.RDFExtractorConfig

Tedy bude treba napsat nejaky script na prepis konfiguraci a nebo je zahodit. Udelat znovu konfigurace je tak na 2-3h, na jak dlouho je ten script odhadem?

**Comment by tomas-knap** [comment]
Udelam si to rucne, nereste. Nicmene ten puvodni problem tohoto issue zustava, mrkni na to prosim Honzo, pripadne prosim diskutuj s Bohuslavem. Opet mozno vyzkouset na dbpedia pipeline - uz normalne sebehne, ale kdyz kliknu na show log, tak mi vyskoci ta chyba.

**Comment by tomas-knap** [comment]
tak jsem vymazal logy a vyresilo se to.

**Comment by tomas-knap** [comment]
Tak uz jsem na to narazil, mrkni na odcs.xrg.cz na pipeline [INTLIB] Decisions from nsoud a tu si pust v debug modu. Zkus si pak proklikavat logy, mrkni trebas na vystup jTaggerAnnot DPU.

**Comment by tomas-knap** [comment]
tohle je dulezite, bez toho se nedaji pipelines ladit, prohlizet logy, ...

**Comment by tomas-knap** [comment]
Check that logback is using UTF-8 encoding of the messages

**Comment by janvojt** [comment]
OK, I think I know where the problem is. When logback connects to database, it uses the same virtuoso configuration for connection as backend application. This includes encoding, which we configured to be UTF-8. So the encoding of communication between logback and virtuoso should be fine.

The way it works is, that DPU uses String, which is pretty much just a string of bytes. This String is passed to logback, and logback passes the same String to JDBC, which is configured to use UTF-8. Therefore as long as this string of bytes logged in DPU is a valid UTF-8 string, it must get to the DB engine correctly.

Now the problem is, that the database column for log message has a maximum length of 254 characters. Because of this, logback checks the length of every string it is about to save in DB. If it is longer, logback truncates it with classic Java call `return s.substring(0, 254);`.

At a first glance this looks OK, but in reality it is very dangerous to cut the string this way if we do not know what is inside. Java uses UTF-16, which counts 2 bytes exactly for each character. However UTF-8 uses a variable byte-length of up to 6 bytes. Therefore for example if the character at the position 253 in the String is a 4-byte character, it would be cut in half and could very likely form an invalid character in UTF-8.

This is still just a theory, but the message "partial character at the end" strongly suggests it. It would also explain why it is hard to reproduce with few data, as the chances of a long character across 254. position is not that likely.

I will adjust VirtuosoAppender for logback, and hopefully this will resolve it.

**Comment by tomas-knap** [comment]
I think that restricting the log to 254 is too restrictive, do we need such restriction, does it bring significant performance gain when compared with unrestricted log size?

**Comment by janvojt** [comment]
The restriction of 254 characters is only applied to arg[0-2] columns. I checked, and the problem is not in these columns. The column causing the problem is formatted_message, which is of practically unlimited length. In fact, some of the log messages exceed 50 000 characters in length, which I think is crazy.

Anyway, I am failing to find a row that is causing the problem by debugging the Java call, because the select query is too big (it seems like lazy query container is not respecting limit and offset when constructing query and is loading almost everything). The exception is thrown in Virtuoso JDBC driver (ConversionException), for which it is complicated to obtain sources.

I tried dumping all the contents of column formatted_message into a file and validating it as UTF-8 text. Iconv says it is valid and does not contain any bogus characters.

The weird thing is, that by default Virtuoso seems to truncate BLOBs which are too long when connecting with isql. If I add option `BLOBS=on`, it stops truncating. I tried adding this option to JDBC connection string, but to no avail.

So far, I believe the problem is caused by some truncation of long strings by virtuoso. Error only occurs in debug mode, when extremely long logs are generated (whole xml files). Will inspect further tomorrow...

**Comment by tomas-knap** [comment]
Thanks for the report, hopefully you will find the cause of the problem
tomorrow.

Tomas

**Comment by tomas-knap** [comment]
I will check the encoding of the logged messages

**Comment by tomas-knap** [comment]
Should be solved by NVARCHAR fields

**Comment by janvojt** [comment]
Converting column types to NVARCHAR will not help, because serialized configuration is stored in VARBINARY column.

**Comment by tomas-knap** [comment]
But it can be stored in LONG NVARCHAR, right?
@skodape  pls discuss

**Comment by skodapetr** [comment]
The configuration should not be a problem .. as we can serialize it into string .. instead of byte[](it's just xml .. for current use) but looks like simple switch in database does not do the job .. (some exceptions ) but we should try this .. as we face the similar problem as with configuration with logs (messages) ..  so it looks like this problem can appear everywhere where we have  national characters and big data.

Other solution can be MySql .. restrict the sice of "data". The base encoding may works for configuration but still there is problem with logs etc .. we would have to encode every "big" string in application.

**Comment by tomas-knap** [comment]
Petre, je treba nejak explicitne zkouset ze  VARBINARY -> LONG NVARCHAR je ok? Pripadne uz jsi to zkousel kdyz jsi delal skript pro Varchar -> NVarchar? Ja jen, abychom vedeli, ze tohle neni problem a mohl jsem to zitra hodit na ODCS - ostrou verzi

**Comment by janvojt** [comment]
> je treba nejak explicitne zkouset ze VARBINARY -> LONG NVARCHAR je ok?

Ja som to skusil zmenit, ale hadzalo mi to chyby. Zrejme JDBC to nepobere, pretoze typ v jave je byte[] a typ v db je varchar. Samozrejme by sa to dalo zmenit na String, ale ked tak to skusim az v Prahe. Mam tu len PC s 2GB RAM, takze som to skusal len cez ssh a nie je to zrovna pohodlna praca. Kazdopadne teda len zmenit datovy typ v db nestaci.

**Comment by skodapetr** [comment]
U mě hlavní potíž byla pokud ten LONG NVARCHAR  byl empty (a to né u konfigurace) jdbc se to pak pokusil převést na String a přitom to spadlo (jen pokud je emptz.)

V jedné branchi jsem tedy vrátil zpět omezení na velikosti některých fieldů a připravil na vyzkoušení Tomášovi, jeslti to pomůže .. tedy teď už je to spíše na něm aby to ozkoušel.

**Comment by tomas-knap** [comment]
does not happen in experimental branch
