### ISSUE TITLE
Testing DPUs 

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#603]
1. getJarPath() is not accessible during testing (how to fake that?). In my code, there is: jarPathString = context.getJarPath().getCanonicalPath();, which I am using to get certain resources from the JAR. See URIGenerator DPU for details. Easy solution woulld be to point to working dir /jar-name, where the jar must be present (jar could be deployed there as part of maven build)
2. Would it be possible to add possibility to test not only against local RDF but also virtuoso? Reason: certain issues are Virtuoso specific. So it would be best if I can choose whether testing against local RDF or virtuoso, speciy connection string

**Comment by skodapetr** [comment]
1) the problem is .. that the test are (best to my knowledge) executed before the jar file is assembled. So if we wan't this functionality we have to take another way. What about provide path .. to resource directory? If it is possible, I do not know now.

2) I added possibility for this. But you have to set the Virtuoso connection your self. It is not possible now to use configuration.properties. Take is as a quick solution .. we may discuss something better on next meeting.

**Comment by tomas-knap** [comment]
1) The problem is that getJarPath cannot be used when mvn installing the given DPU. But as long as JAR file was generated, we can specify a path to it. So I think that we can do the easiest thing - user will provide path to JAR file and such test should be excluded from automated tests

2) Ok, please provide an example in the documentaiton how to set the connection
