### ISSUE TITLE
SPARQL Transformer - possibility to work with more graphs

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#608]
Motivation: 
I have a SPARQL query, which CONSTRUCTS certain data X based on named graph A. However, for the construction of the data X, another named graph B (another input) is needed. However I cannot run the construct against merged named graphs A and B, becuase that would construct more data then needed. Therefore, the role of input named graphs A and B is different. That is quite a common situation.

To realize that, I need:
1 To be able to specify for SPARQL transformer that he expects one mandatory input and other optional inputs (I will solve that with Petr)
2. I have to be able to specify in the query graph patterns (triple patterns with information about graphs the data is coming from). This is standard expression supported by SPARQL 1.1, e.g. the query: 

For example, query construct {?s ?p ?o. ?s ?p ?y}  where { graph http://myGraphA {?s ?p ?o} graph http://myGraphB {?s ?p ?y}} constructs certain data from graph http://myGraphA and certain from http://myGraphB. 

The problem is that I do not know, in the time of writing the query, the named graph in which the data will be, I only know the names of data units. 

---

Solution: So the user writing the query to the SPARQL transformer dialog should be able to write something like:

construct {?s ?p ?o. ?s ?p ?y}  where { graph ?g_A {?s ?p ?o} graph ?g_B {?s ?p ?y}}

But before the execution of the query, the placeholders ?g_X are replaced with the input graphs being used by the input named X. So if there is input data unit called "inputA" and "inputB", the placeholders are ?g_inputA ?g_inputB. And before the execution ?g_inputA is replaced with <{namedGraphBehindInputA}>

**Comment by tomesj** [comment]
OK, but I need access to all inputs, so I can set the real names of graphs (for replace placeholders).Currently we have only one input

Where I see problem:
If you have more inputs, you have to define mapping between graph names and placeholders.

Because if you have specific construct using some triples for one graph (for example which has only predicate http://my.predicate) a all triples for others graphs. Its important to know, which graph use where (it depends on the order).

But logic of DPU (name of graphs) and (construct) query are separated. - I dont know, how you can make these necesarry mapping.   

Or what is your idea to solve this ?

**Comment by skodapetr** [comment]
Well nice use case .. so from my point of view .. I see it as a small challenge .. 

Jirka: I thing there is no problem on your side ... for better explanation some pseudo-code..

```
for (placeholder : SPARQL) {
   bool replaced = false;
   for (input : InputDataUnits) {
      if (input.getName == placeholder) {
         placeHolder = ( (RDFDataUnit)input).getGraphName();
         replaced = true;
         break;
      }
   }
   if (replaced == false) {
       context.sendMessage(Error, "Missing input data unit for placeholder ...");
       return;
   }
```

The challenge (from my point of view) is in the InputDataUnits. Jirka is right that we have no support for optional number of input graphs. 

What can be easily accomplished is .. that we define three more optional input DataUnits  (see InputDataUnit annotation's documentation for more details) .. and then we pick one of them. 

The better would be to have annotations for List<> .. which take all otherwise unused DataUnits and put them into the list. 
We need support in mapping GUI for this as the current state is following:
you get list of outputs list of inputs .. and you create n:m mapping. 

The problem is, you can not define your own name .. which I believe is what you need in this case. 
You need a way how to say "take this DU .. put it into this List<DP>  and name give it name Y". 

So what I propose is .. take some reasonable number of possible inputs like ... 5 ... add 5 optional input DU and do all the magic.
As a prove of concept I believe this can be archived relatively easy in a day or two. And it will also quickly provide environment where you can this this for RDF problems.

Until we decide how to support List<> mapping.

**Comment by tomesj** [comment]
I originally thought that the name for placeholder in query can be any of random name you want (you choose name variable for graph without knowledge DPU name). 

From what Peter says, must it be the same as the name of the DPU. Then it makes sense - see pseudocode. It solves my previous mapping question.

**Comment by tomas-knap** [comment]
Jirka, the placeholder ?g_XX must be in a form that XX is the name for certain data unit, input or output. So I would also suggest to start with a simple version, that means to provide e.g. up to three optional data inputs with certain fixed named. No additional output data unit. 

Jirka, so suppose that there are input data units for SPARQL transformer input,input2, input3, input4. THen you have to provide at least certain input data unit mapped to "input" (this data unit is mandatory), but you may also map to input2, input3, input4 (these are optional). In the query, you may use variables ?g_input ?g_input2 ?g_input3 ?g_input4. Every such variable corresponds to the underlying graph of the corresponding data unit. Is that clear?

SO you have to: 
1) add optional data units to SPARQL transformer, use names input,input2, input3, input4
2) when user saves SPARQL query, except of normal validation, you also check that all the placeholders correspond with certain data unit name. If not, error is thrown and the query cannot be saved. 
3) during execution, implement the rewriting of ?g_X with the proper graph the data unit with name X is working with (as above in the code).

**Comment by tomesj** [comment]
Yes, for me, is it clear now :-) 

But I have one question - if you use placeholders like ?g_A, ?g_B, ... in a query is a problem with validation. It dont passed.

Solution:
I) Temporarily replace this placeholder with generate graphName. And if is known concrete DPU - replace to right graph.

Example:
DPU A 
1) origal graph name: http://myGraphA 
2) placeholder in query: ?g_A
3) Temporary graph name: http://temp/A.
4) If have info about input concrete DPU - replace http://temp/A to http://myGraphA

II) Put out validation for construct query contains placeholders for graphs

I am for variant I). Do you agree ?

**Comment by tomas-knap** [comment]
Yes, but please use graphs in the form http://graphForDataUnit_XX where XX is the name of the data unit.

**Comment by tomas-knap** [comment]
Please let me know when I can try that

**Comment by tomesj** [comment]
OK - I will use your graph form.

**Comment by tomas-knap** [comment]
Comment PlaceholdersHelper class in SPARQL transformer, so that everything important from this issue is in the comments - especially the way how the replace work

**Comment by tomas-knap** [comment]
I tried it and got:

![screen shot 2013-11-21 at 4 54 33 pm](https://f.cloud.github.com/assets/3014917/1593007/43784ee4-52c5-11e3-9531-a710f26adb2e.png)

First, the spelling is wrong!
Second, there should be reason where the problem is - not just "it was not replaced", but also "WHY" it was not replaced

**Comment by tomas-knap** [comment]
Second message with stacktrace - adjust formatting - no space second line

Execution failed because: Graph for DPU name optional1 was not replasedcz.cuni.mff.xrg.odcs.commons.dpu.DPUException: Graph for DPU name optional1 was not replased
    at cz.cuni.mff.xrg.odcs.transformer.SPARQL.PlaceholdersHelper.replaceAllPlaceHolders(PlaceholdersHelper.java:126)
    at cz.cuni.mff.xrg.odcs.transformer.SPARQL.PlaceholdersHelper.getContructQuery(PlaceholdersHelper.java:159)
    at cz.cuni.mff.xrg.odcs.transformer.SPARQL.SPARQLTransformer.execute(SPARQLTransformer.java:72)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.executeInstance(Executor.java:211)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.execute(Executor.java:322)
    at cz.cuni.mff.xrg.odcs.backend.execution.dpu.Executor.run(Executor.java:398)
    at java.lang.Thread.run(Thread.java:722)

**Comment by tomas-knap** [comment]
I have the following configuration: 

![screen shot 2013-11-21 at 4 57 18 pm](https://f.cloud.github.com/assets/3014917/1593026/a030b1e4-52c5-11e3-9d45-170e8b5c8343.png)

Why there was a problem and optional1 was not replaced?? The variable used is g_optional1 and input is optional1

**Comment by tomas-knap** [comment]
Also the problem should have been thrown much more earlier - during validation of the SPARQL transformer query, if there is a variable, which does not match with certain input data unit, errror "variable cannot be resolved" should appear when saving and validating the configuration - we discuss that above: 2) when user saves SPARQL query, except of normal validation, you also check that all the placeholders correspond with certain data unit name. If not, error is thrown and the query cannot be saved.

**Comment by tomesj** [comment]
Add needed inputs, try using in pipelines, add validation to dialog for this DPU- solved and prepare for testing and close.
