### ISSUE TITLE
Unsaved changes when they should not be shown

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#609]
I switch to certain DPU template in DPU template menu item. Next, i replace DPU template and then notificaiton: "Unsaved changes" appears.

Solution: Such message should not appear if I only replace JAR, because the new JAR is saved when the replace is finished?

**Comment by tomas-knap** [comment]
Also, when I confirm such notification and click to a different DPU template, it appears again
Maria, please test the notifaciton message by clicking on different templates, changing different values on different tabs and observe the behaviour

**Comment by kukharm** [comment]
I can't reproduce this by replace, but a get this bug other way:
I create new DPU Template by "Create DPU template" button and load Silk_Linker_Extractor-1.0.0. 
Than in the tree i select Silk Linker Extractor, i don't make any changes and select other DPU in the tree but confirmation window is appear.

As shown by debug, function hasConfigChanged() (na AbstractConfigDialog) that used for check changes in configuration window always return true if the text area in Silk Linker Extractor is empty. That is why confirmation dialog is appears.
Petr, please, look to the function hasConfigChanged(). I can't reproduce it on other DPUs only on silk, but i think bug that has Tomas is also because  hasConfigChanged() return true where it would not be.

**Comment by skodapetr** [comment]
Well .. the behaviour for silk was basically right. There were no configuration (null) and so even empty configuration was "modified" ie. different from null.

Now on DPU import default configuration is created, so it should be ok now. 

But .. for example .. the silk default configuration is not valid .. we should emphasise that the default configuration must be valid .. at least in terms of isValid method. 
If you import DPU with such configuration .. then you get warning for invalid configuration when you open such DPU.

And same as Maria I was unable to reproduce this by using "replace".
