### ISSUE TITLE
Canvas improvement - Undo button

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#62]
Every change on canvas is saved to stack and it is possible to go back to previous version of pipeline in the scope of current changes since last save/commit.

**Comment by tomas-knap** [comment]
Undo funguje tak, že ukládá stav grafu při přidávání a odstraňování hran/DPUček, neregistruje tedy změny v layoutu. Pokud to takto nevyhovuje/bylo to myšleno jinak, tak mi to prosím napište, nejlépe přímo k issue. Je ovšem potřeba vzít v úvahu, že při posunování DPU po canvasu se ukládá pozice často, znamenalo by to hodně kliknutí na undo. Ale třeba uložení při změně layoutu by možná stálo za zvážení.

**Comment by tomas-knap** [comment]
Bohuslav, yes, saving layout change seems to be reasonable requirement. Because it may happen that the user is not satisfied with the results of the layouting and needs to roll back. Could you please add this? 

Regarding the changes in position, it would make sense to store the current position of all dpus when you store any of the important changes (dpu added/removed, edge added/removed, layout changed). If the user clicks undo, it will roll back the last important change and restores the position. Motivation for that: It may be confusing, if I click UNDO and certain DPU dissapears but old position is not restored. What do you think?
