### ISSUE TITLE
Increase number of rows in pipeline list at least to 20

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#649]

**Comment by tomas-knap** [comment]
Or if it is easy, just fill all the space available on the page with the table for pipeline list, scheduler events, exec monitor. This is a better solution.

**Comment by tomas-knap** [comment]
No fixed integer value should occur in the code, such as: 

![screen shot 2013-10-15 at 2 56 45 pm](https://f.cloud.github.com/assets/3014917/1333662/5d123534-3599-11e3-9ae7-5ff3c24091f2.png)

If needed, constant may be used

**Comment by bogo777** [comment]
It would be quite complicated if the number of rows in the table was dependent on the user screen size. For smaller screens there would be only a few rows, which is maybe more unpractical than having to scroll down a bit. What would we do if the user would resize browser window? Would the tables be resized too? Again, if the window is small, there would be few rows. Also, execution monitor with debug is quite complex for table resizing(different tables have rows with different height etc.)

I propose to select one screen resolution for which the layout would be optimized(preferable quite big resolution), since vertical scrollbars(shown for smaller screens) are part of almost every web page. Or we could use some rounded numbers for the main tables(as we do now = 20 rows per page).

**Comment by tomas-knap** [comment]
View should fill the whole space, rows always 20

**Comment by tomas-knap** [comment]
When done please leave it with low prio

**Comment by tomas-knap** [comment]
User may specify in the settings the fixed number of rows for the tables
