### ISSUE TITLE
NPE when moving DPUs on canvas

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/odcs#652]
![image](https://f.cloud.github.com/assets/718827/1333083/23218954-358c-11e3-9e11-c035374bcdb0.png)

**Comment by tomas-knap** [comment]
To reproduce: 
Create new pipeline, put SPARQL extractor there. Then try to "debug to the given DPU". Error occurs - cannot save pipeline, because no name. However, as looking to db, the pipeline was actually saved (see 102 DPU instance). This is probably the root cause of the problem. 

 1    SPARQL Extractor    0           <object-stream> <cz.cuni.mff.xrg.odcs.extractor.rdf.RDFExtractorConfig> <SPARQL__endpoint>http://dbpedia.org/sparql</SPARQL__endpoint> <Host__name></Host__name> <Password></Password> <GraphsUri class="linked-list"> <string>http://dbpedia.org/</string> </GraphsUri> <SPARQL__query>CONSTRUCT {&lt;http://dbpedia.org/resource/Prague&gt; ?p ?o} where {&lt;http://dbpedia.org/resource/Prague&gt; ?p ?o } LIMIT 100</SPARQL__query> <ExtractFail>false</ExtractFail> <UseStatisticalHandler>false</UseStatisticalHandler> </cz.cuni.mff.xrg.odcs.extractor.rdf.RDFExtractorConfig> </object-stream>    <DB NULL>   1
 2    RDF File Loader     0           <object-stream> <cz.cuni.mff.xrg.odcs.loader.file.FileLoaderConfig> <FilePath>/tmp/dbpedia.rdf</FilePath> <RDFFileFormat>RDFXML</RDFFileFormat> <DiffName>false</DiffName> </cz.cuni.mff.xrg.odcs.loader.file.FileLoaderConfig> </object-stream>    <DB NULL>   5
 102      SPARQL Extractor    0       <DB NULL>   <object-stream> <cz.cuni.mff.xrg.odcs.loader.file.FileLoaderConfig> <FilePath>/tmp/dbpedia.rdf</FilePath> <RDFFileFormat>RDFXML</RDFFileFormat> <DiffName>false</DiffName> </cz.cuni.mff.xrg.odcs.loader.file.FileLoaderConfig> </object-stream>    0   1

Solution: If there is an error and cannot saved is shown. it must not SAVE the dpu instance. 

Further, even in case of such problems, the method working with node (such as node.move) must check that the node object is not null.
