### ISSUE TITLE
Scheduling not working properly

### ISSUE THREAD

**Issue by bogo777** [mff-uk/odcs#661]
I scheduled DBpedia pipeline -> I selected only the pipeline, left everything else as it was -> current date and time, repeat every day. Then pipeline is running again and again, I have 20 execution in 10 minutes.

**Comment by skodapetr** [comment]
Pravda .. koukal jsem na to a vypadá to na podobný problém jako v #651 (asi) v kódu se volá.

```
schedule.setLastExecution(new Date());
...
scheduleFacade.save(schedule);
```

Kód je z backend.Scheduler.execute

Nicméně v DB zůstává lastExecution s hodnotou null .. a tedy se backend pokouší stále pouštět znova. Přeřazuji tedy na Honzu, jestli je toto u něj replikovatelné .. na základě rychlého debugu to vypadá, že se prostě ta hodnota do DB neuloží.

**Comment by tomas-knap** [comment]
Potvrzuju

![screen shot 2013-10-17 at 10 55 17 am](https://f.cloud.github.com/assets/3014917/1350386/fb09c9ac-3709-11e3-803f-1db7345fa01e.png)

**Comment by janvojt** [comment]
The problem seems to be that  transactional annotations are ignored.

When save is called with schedule, the schedule is already persisted in DB, so merge is called. However merge itself only merges in the cache and does not flush the merged object to the database. It is to be flushed when transaction is committed, however there is no transaction. Therefore the merged object is never flushed to DB.

I will investigate why transactional annotations are being ignored.
