### ISSUE TITLE
Problems when copying pipeline

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#747]
To reproduce: 

Go to odcs.xrg.cz, try to copy ARES test pipeline. Observe the result, the pipeline is missing certain DPUs/edges.

![screen shot 2013-11-13 at 9 34 05 am](https://f.cloud.github.com/assets/3014917/1529801/fe0a0960-4c3e-11e3-86c3-af204f6db137.png)

**Comment by tomas-knap** [comment]
I managed to reproduce that on odcs, where the deployed version is before weekend.

**Comment by janvojt** [comment]
I reproduced on odcs.xrg.cz, however I cannot reproduce on localhost. I tried to copy ARES test, also even more complicated pipelines, and did not encounter any problem. I will try to download the database from odcs.xrg.cz to see if I can reproduce with same data.

**Comment by tomas-knap** [comment]
Honzo, zkus prosim, ja ti dam vedet, jestli se to objevuje i na posledni
verzi

**Comment by tomas-knap** [comment]
It is also problem in the latest version, see odcs.xrg.cz with latest war

**Comment by tomas-knap** [comment]
Plese look on that

**Comment by janvojt** [comment]
I copied the database from odcs.xrg.cz in somewhat inconsistent state, because it was running while copying data under virtuoso's hands. Anyway, I can reproduce the problem on localhost. So far I found that the pipeline is actually copied correctly, database contains correct and complete data for copied pipeline graph. The problem is, that it is not read completely from the database. It is also pretty random what part of the graph is missing among different copies, but is consistent on a single copy.

At a first glance it seems like a problem with caching. However it is not, because I tried stopping virtuoso, stopping tomcat, and starting both again and the copied pipeline still could not be read.

It is just weird.

**Comment by janvojt** [comment]
The problem on my localhost was caused by invalid serialized configuration of 2 DPU instances in DB. After I deleted these configurations, the copied pipeline started to show up correctly immediately afterwards. I cannot confirm this was the same bug as on odcs.xrg.cz, because the database I copied was in somewhat inconsistent state.

To investigate further, I need the database on which the issue can be reproduced, or to connect to jvm on odcs.xrg.cz with a debugger. Both these actions require root privileges. So what do we do next Tom?

**Comment by janvojt** [comment]
Problem is with the (top) XSLT DPU instance configuration. Its serialized configuration on ARES test pipeline in database is 24186 bytes long, however when it is read into the object attribute, its length is only 24125 bytes. First I thought it could be caused by some truncating of long BLOBs, however the other XSLT DPU has a much longer configuration and it is read and copied just fine.

**Comment by tomas-knap** [comment]
Well, than re-saving the original ARES test pipeline should help, right? But please backup the configuration first, in case of problems, so that Jakub does not need to write it again

**Comment by janvojt** [comment]
I tried resaving configuration, but the problem still persists. Somehow eclipselink just does not read all the data before copying, and then the serialized configuration in DB is invalid. I will try to reproduce on a trivial pipeline with just a single DPU and see where it gets me.

**Comment by janvojt** [comment]
The root cause is actually "Virtuoso Communications Link Failure (timeout) : malformed input around byte 1369". The character at this byte is `é`. Therefore, it is a problem with diacritics, they somehow get malformed in the process of copying.

I tried removing all the accented characters from XSLT configuration and the problem disappeared.

**Comment by janvojt** [comment]
I suspect that it is caused by some odd bug in Virtuoso, as it is quite unpredictable when the bug takes effect. Some strings with diacritics are saved correctly, some strings with exactly same accented characters are saved incorrectly.

Because of this, debugging is very problematic. I suggest we work around this problem by encoding the serialized configuration into Base64 and then saving it into database. It would be ineffective (serialized configuration would be 4 times longer), however should solve the issue.

**Comment by tomas-knap** [comment]
Why does it appear when pipeline is copied and not when it is saved/reopened?

**Comment by tomas-knap** [comment]
What is the diff when copy is created?

**Comment by janvojt** [comment]
> Why does it appear when pipeline is copied and not when it is saved/reopened?

Because the copied string is invalid. I need to try to log the byte array and see what encoding is actually used. Although it should not matter, you should get what you typed in...
Byte array is copied with simple clone(), so I assume it is messed up somewhere in JDBC or in Virtuoso. However I could not get the sources of Virtuoso JDBC to match the compiled code, so I cannot debug inside JDBC.

> What is the diff when copy is created?

Accented characters are broken.

**Comment by tomas-knap** [comment]
Source code for jdbc 
https://github.com/openlink/virtuoso-opensource/tree/develop/7/

Akorat je to mozna pro to Virtuoso 7...

**Comment by janvojt** [comment]
Ano, uz davno si mi pisal ze tam maju zdrojaky. Nasiel som ich tu https://github.com/openlink/virtuoso-opensource/tree/develop/7/libsrc/JDBCDriverType4. Ale nejdu mi pouzit. Je tam classpath virtuoso.jdbc2, a v JDBC driveri je virtuoso.jdbc4. Skusal som ten adresar aj manualne premenovat, ale nepasovali tie zdrojaky (alebo netbeans to nepobral). Ale aj tak neviem ci ma cenu debuggovat ten JDBC, nie je to zrovna najjednoduchsi kod. Nestacilo by to proste zakodovat do base64 ako som pisal?

**Comment by skodapetr** [comment]
Jen dotaz .. pokud je to problém s konfigurací .. ve keré je soubor, tj. string ..  kde je znak `é`, tak pokud ten znak napíšu třeba do cesty k souboru  (string) pro file extractor, tak to taky spadne?

Nebo jsem mimo?

**Comment by tomas-knap** [comment]
Mozna bychom jeste mohli zkusit rucne vytvorit kopii te pipeline, ktera obsahuje jen ARES/XSLT DPU a ty konfigurace vyplnit stejne. Problem imho nebude v tech zakladnich DPUs - extraktor/loader. 

Ad Petr: Jj, to je divne, bo pro FIle extractor narodni znaky fungujou dobre.

K tomu BASE64, moc se mi to nelibi, bylo by potreba zakodovat i stavajici konfigurace, musime to napsat Alexovi a dalsim,ze si musi zakodovat konfigurace. Navic na prvni pohled neni videt v DB konfigurace.

**Comment by janvojt** [comment]
> pokud ten znak napíšu třeba do cesty k souboru (string) pro file extractor, tak to taky spadne?

Uz som o tom pisal, ale chova sa to fakt divne. Z mojho testovania mi vyslo, ze to pada len na niektorych stringoch obsahujucich narodne znaky. Ked do konfiguracie ulozim len problemovy znak, tak to funguje. Ked ma nejake "okolie" standardnych znakov z ASCII tabulky, tak pre niektore okolie to funguje, pre niektore nie. Snazil som sa dohladat co najkratsi problemovy string pulenim intervalu, ale chovalo sa to velmi divne a ked som mal cca 50 riadkov tak som to vzdal.

**Comment by janvojt** [comment]
> rucne vytvorit kopii te pipeline, ktera obsahuje jen ARES/XSLT DPU a ty konfigurace vyplnit stejne

To som samozrejme skusal, uz davno som prisiel nato, ze problem je len v XSLT konfiguracii. Takze ano, ak vytvorim pipeline len s jednym XSLT DPU s rovnakou konfiguraciou, tak sa neda skopirovat.

**Comment by janvojt** [comment]
Petr commited a modification in commit 9e80d6f3, where when copying configuration serialized string is converted to UTF-8 with `String.getBytes("UTF-8")`. This method always replaces malformed-input and unmappable character sequences with UTF-8's default replacement byte array. Therefore the pipeline should be copied successfully even with accented characters, but they may be replaced. This still does not resolve issue.

**Comment by tomas-knap** [comment]
So what is still missing to be solved?

**Comment by janvojt** [comment]
OK, I did some testing, and it seems Petr's solution works. I was suspecting it would obfuscate serialized configurations, but that would be true only if we were serializing to binary data (we are serializing to XML).

There is no guarantee that national characters in configuration will not be obfuscated. However, from my testing it seems Czech characters are OK. As long as we won't be using some unusual characters (e.g. Chinese), I think we can consider this issue solved.
