### ISSUE TITLE
Browse/Query - run and download - formats not working in the combo box

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#772]
When selecting format TSV, error occurs. Solution: remove TSV from the choice. this happens also for some others. At the end the content of both rdf format combo boxes on the browse/query tab should be the same!!

**Comment by tomesj** [comment]
No, TSV and all formats works fine. 

Problem is only that format as:
XML, JSON, CSV, TSV 
can be used only when your have SELECT query, but there are NOT for using CONSRUCT queries !!!

Author of the class RDFQueryView where the problem is Bohuslav.
Bohuslav has here only notification as: BAD FORMAT SELECTED !!! If you can use it for RUN and DOWNLOAD in construct case.

Other formats as:
RDF/XML, TTL, NTRIPLES, TRIG, TRIX you can be used by both type (SELECT, CONSTRUCT).

Possible solution:
1] Change notification: This selected format can not be used for CONSTRUCT query-
2] 2 comboboxes - format values for Both, formats only for SELECT
3] Other solution - ?

What do you think ?

**Comment by tomas-knap** [comment]
Well than the notification may be adjusted. If the user specifies a wrong format, explanation should be given that this format is supported only for SELECT query.

**Comment by tomas-knap** [comment]
Jirka, pls suggest Bohuslav what should be in the notification

**Comment by tomesj** [comment]
Problem solved :-) Prepare to close
