### ISSUE TITLE
Debug button on pipeline list opens wrong exec record detail or no detail

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#812]
To reproduce: run pipeline in debug mode. It opens a wrong execution (i the currently being executed is still in queued state). If you run the pipeline in debug mode for the first time, no exec record detail is selectedbecause when selecting, the pipeline is still in queued state probably and there is no other.

![screen shot 2013-11-22 at 10 45 44 am](https://f.cloud.github.com/assets/3014917/1599608/e7b10362-535a-11e3-86f9-36cd3f778df6.png)

**Comment by bogo777** [comment]
The problem is in PresenterWrap, where method enter() in which the parameters are set, is called AFTER method enterPresenter() which uses the parameters. 

So for first request, there aren't any stored parameters and for the next requestes it is always one request later.

As @skodape is author of navigation, maybe he would be the best person for the fix. Or we cas discuss it in the meeting and I can then fix it.

**Comment by skodapetr** [comment]
This is true .. and it's a little bit unfortunate. The enter method .. will be always called after the enter presenter .. as enter presenter is called by PresenterWrap when it's set .. and enter when it's shows. 

What we can do is:
a) presenterEnter will create the layout .. without any data (I remove the parameter)
b) then the setParameter will be called (with the parameter from enter) .. and here should presenter set the data

Can we use this solution? I think it van work nicely .. 
@bogo777 can you please give us your opinion ?

The reason why it's so tricky is .. that I do not change the navigator class directly so I do not have full control over it.
