### ISSUE TITLE
Test how the private/public pipeline works

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#855]
Look at https://github.com/mff-uk/ODCS/issues/713, where it is described how it should work. 

Test then the following: 
- create a pipeline under user x
- user x runs the private pipeline. Check that user y cannot see the execution record. 
- log as user y. You should not be able to see private pipeline. Log as user x, publish pipeline, check that user y can see it. 
- check that when publishing pipeline with a private DPU, it is made public. 
- log as y. Try to delete pipeline create by x, which should work. Log as x, there should not be any pipeline because it was deleted. 
- in the cases above, use normal users, with no Administrator roles. NExt, try to add Admin role to user y and repeat the above points. user y should see even private pipelines of user x, his executions.

**Comment by kukharm** [comment]
tested on commit 812825382269de14969d2e9bd72230ff71a8e132
Author: Maria Kukhar mari.kukhar@gmail.com 2013-12-01 23:30:07
Committer: Maria Kukhar mari.kukhar@gmail.com 2013-12-01 23:30:07
Parent: bd3374d7d43730ad95b473a9605b7fba665cc61a (Changing the text color of checkbox. Closed #852)
Branches: master, origin/HEAD, origin/master

"Log as user x, publish pipeline, check that user y can see it."
User y see published pipeline in Pipelines section but do not see it in the "Schedule a pipeline" dialog in Scheduler section.  When user y open  "Schedule a pipeline" dialog by "Schedule" button in Pipelines section he can see it. (issue #860)

One user create private DPU, then another user (he don't see the private dpu of another user) try to create dpu with the same .jar file name and get the error message 
![errordpu](https://f.cloud.github.com/assets/3471169/1652442/dbc52af4-5b13-11e3-84d1-7126c45896ac.jpg)

is this situation correct?

When user y try to change public pipeline created by user x he gets a message
![accessex](https://f.cloud.github.com/assets/3471169/1652458/8c4615aa-5b14-11e3-8dc1-3f840e792e9d.jpg)

is it correct?

"log as y. Try to delete pipeline create by x, which should work. Log as x, there should not be any pipeline because it was deleted."
Delete don't work (user y have only User role). I press delete button appear confirmation window, i confirm deleting and nothing happens. (issue #859)

**Comment by tomas-knap** [comment]
Created #861 , #862

**Comment by tomas-knap** [comment]
Please add this report to the confluence testing page. Please also separated each testing to a new page

**Comment by kukharm** [comment]
https://grips.semantic-web.at/pages/viewpage.action?pageId=50932889
https://grips.semantic-web.at/display/LOD2/Testing
