### ISSUE TITLE
Description of DPU template not shown?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#883]
When there is description in pom.xml, it is not shown in the DPU template dialog

![screen shot 2013-12-05 at 5 22 00 pm](https://f.cloud.github.com/assets/3014917/1684311/7d793540-5dc9-11e3-8723-c1b562ebd7dc.png)

**Comment by skodapetr** [comment]
It's not .. it's the user-provided description .. the description of JAR is slightly lower on this dialog.
Also if the description is empty, then on pipelnine-canvas the config-provided description is used. We may emphasize this a little bit more ..

**Comment by tomas-knap** [comment]
Ok, but I could imagine that the read-only description from pom.xml will be shown instead of "Maven parent project..." (see above), so that description filled in by the developer (who could be a different person than the person importing the DPU to the app) is not lost

**Comment by skodapetr** [comment]
Well .. the problem here is that the geocoder is written according the old tutorial. 

The description and version are for some time (on Jakub's request) no longer under properties tag, but directly under the root tag .. see DPU_Template pom.xml for more details .. what we see here "Maven parent .. " is used description from parent maven project.
