### ISSUE TITLE
Problem with pipeline dbpedia extractor

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#932]
Pipeline dbpedia extractor has one SPARQL extractor and one loader. However, when running the pipeline, events contain: 

![screen shot 2013-12-17 at 9 29 29 am](https://f.cloud.github.com/assets/3014917/1762526/b1bb5dd4-66f6-11e3-9a67-c50eab692a8b.png)

So there is no record for SPARQL loader
Petre, please check that. If you do not have time today and tomorrow, reassign on Jirka.

**Comment by skodapetr** [comment]
Based on log .. (not events) both DPUs have been executed, also the event has been published, otherwised there would not been log about starting the second DPU.

I hope that the backend file log gives me more info.

**Comment by tomas-knap** [comment]
So it seems that certain events are not flushed properly?

**Comment by skodapetr** [comment]
The problem was in the invalid configuration .. of the Loader (it even show message then the configuration dialog has been opened) .. unfortunately by this .. I close my self the way to test this .. :( but it looks like it has been connected with isValid methods .. it is my fault that there may rise the NPE exception that has been probably the source of the problems ..  the fact that the SPARQL loader and extractors have different validation methods distract my attention ..

But still I have added some exception catches ... into the dpu.executor so it should now be able to withstand such "dpu's behaviour". So it should be fine now.
