### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#940]
When adding new user, is there a difference if I say that user has roles:
1) Administrator and User
2) Administrator only

Is there a difference between 1) and 2)?

**Comment by janvojt** [comment]
No, not in current implementation. The "user" role is used, because it is usually done this way in the frameworks I have seen. In our situation, it is unimportant. But I would keep it for future enhancements. For instance, in future we could decide that we want to allow an anonymous user to be authorized with read-only access just to see what the interface looks like. We could simply add a new role "guest" and configure permission evaluator, to allow only readonly access for this role (even if entities are public-writable).

**Comment by tomas-knap** [comment]
Yes, I understand that. But then the dialog for managing users is confusing - when admininstrator is selected, user should be automatically selected as well, right?

**Comment by janvojt** [comment]
I agree, this can be dealt with in presentation layer, it is a question of UI.

**Comment by tomas-knap** [comment]
In manage users dialogs, if Admin role is selected and copied to right listbox, user role is copied automatically as well.
