### ISSUE TITLE
RDF data validator - doc + localRDF repo?

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/odcs#983]
It seems that RDF data validator is always using local RDF repo. Why? Please add comment to RDFDataValidator DPU main class (contains execute method), which describes how the rdf data validator works (the main idea). It should explain why local RDF repo is used. 

private RDFDataUnit getGoalRepository() {
        if (hasOutput()) {
            return output;
        } else {
            RDFDataUnit tempRepo = RDFDataUnitFactory.createLocalRDFRepo(
                    "tempRepo");

```
        return tempRepo;
    }
}
```

**Comment by tomesj** [comment]
Do you mean class RepositoryDataValidator, not RDFDataValidator !!!

To your questions:
1) I will add description to RepositoryDataValidator with describing how it works
2) To localRepo:
- there are two contructors (you set input + output RDFDataUnit [A], you set nur input RDFDataUnit [B])

[A] is used in RDFValidator DPU
[B] is used ex. as validation data before loading to SPARQL endpoint.

Because our validation is 
- create data file from input 
- validate them using handler + parser as adding file (only with validate data) to output 

In [A] is used set output RDFDataUnit (not fixed localRepo)
- thanks this we validate data and add this to target (defined output)
- output is used in application (not delete after data validation)

In [B] we don´t need output in application 
- we create LocalRDFRepo instance need only for validation (add data from file here)
- after data validation is local repo deleted

How you can see - method getGoalRepository return set ouput in case [A] or create tempRepo as LocalRDFRepo in case [B].

Is it clear ?

**Comment by tomas-knap** [comment]
Ok, thanks for clarification!
